eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
server:
  port: 8002
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true

